url: "https://mapc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/government-types-map" # the subpath of your site, e.g. /blog
title: "Government Types Map" # the name of your site, e.g. ACME Corp.
